/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSupportRouteImport } from './routes/api.support'
import { Route as ApiStateRouteImport } from './routes/api.state'
import { Route as ApiProvidersRouteImport } from './routes/api.providers'
import { Route as ApiNotificationsRouteImport } from './routes/api.notifications'
import { Route as ApiModelsRouteImport } from './routes/api.models'
import { Route as ApiGroupsRouteImport } from './routes/api.groups'
import { Route as ApiGroupMessagesRouteImport } from './routes/api.group-messages'
import { Route as ApiGroupInvitationsRouteImport } from './routes/api.group-invitations'
import { Route as ApiFilesRouteImport } from './routes/api.files'
import { Route as ApiFeedbackRouteImport } from './routes/api.feedback'
import { Route as ApiEarlyAccessRouteImport } from './routes/api.early-access'
import { Route as ApiDatabaseRouteImport } from './routes/api.database'
import { Route as ApiConversationReferencesRouteImport } from './routes/api.conversation-references'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAnnouncementsRouteImport } from './routes/api.announcements'
import { Route as ApiAdminRouteImport } from './routes/api.admin'
import { Route as ApiMemoryExtractRouteImport } from './routes/api.memory.extract'
import { Route as ApiFilesFileIdRouteImport } from './routes/api.files.$fileId'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthEmailVerificationRouteImport } from './routes/api.auth.email-verification'
import { Route as ApiAuthAccountRouteImport } from './routes/api.auth.account'
import { Route as ApiAdminFilesFileIdRouteImport } from './routes/api.admin.files.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportRoute = ApiSupportRouteImport.update({
  id: '/api/support',
  path: '/api/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRoute = ApiProvidersRouteImport.update({
  id: '/api/providers',
  path: '/api/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsRoute = ApiGroupsRouteImport.update({
  id: '/api/groups',
  path: '/api/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupMessagesRoute = ApiGroupMessagesRouteImport.update({
  id: '/api/group-messages',
  path: '/api/group-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupInvitationsRoute = ApiGroupInvitationsRouteImport.update({
  id: '/api/group-invitations',
  path: '/api/group-invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEarlyAccessRoute = ApiEarlyAccessRouteImport.update({
  id: '/api/early-access',
  path: '/api/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatabaseRoute = ApiDatabaseRouteImport.update({
  id: '/api/database',
  path: '/api/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationReferencesRoute =
  ApiConversationReferencesRouteImport.update({
    id: '/api/conversation-references',
    path: '/api/conversation-references',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsRoute = ApiAnnouncementsRouteImport.update({
  id: '/api/announcements',
  path: '/api/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryExtractRoute = ApiMemoryExtractRouteImport.update({
  id: '/api/memory/extract',
  path: '/api/memory/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthEmailVerificationRoute =
  ApiAuthEmailVerificationRouteImport.update({
    id: '/api/auth/email-verification',
    path: '/api/auth/email-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAccountRoute = ApiAuthAccountRouteImport.update({
  id: '/api/auth/account',
  path: '/api/auth/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFilesFileIdRoute = ApiAdminFilesFileIdRouteImport.update({
  id: '/files/$fileId',
  path: '/files/$fileId',
  getParentRoute: () => ApiAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/announcements': typeof ApiAnnouncementsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversation-references': typeof ApiConversationReferencesRoute
  '/api/database': typeof ApiDatabaseRoute
  '/api/early-access': typeof ApiEarlyAccessRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/group-invitations': typeof ApiGroupInvitationsRoute
  '/api/group-messages': typeof ApiGroupMessagesRoute
  '/api/groups': typeof ApiGroupsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/state': typeof ApiStateRoute
  '/api/support': typeof ApiSupportRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/email-verification': typeof ApiAuthEmailVerificationRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/memory/extract': typeof ApiMemoryExtractRoute
  '/api/admin/files/$fileId': typeof ApiAdminFilesFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/announcements': typeof ApiAnnouncementsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversation-references': typeof ApiConversationReferencesRoute
  '/api/database': typeof ApiDatabaseRoute
  '/api/early-access': typeof ApiEarlyAccessRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/group-invitations': typeof ApiGroupInvitationsRoute
  '/api/group-messages': typeof ApiGroupMessagesRoute
  '/api/groups': typeof ApiGroupsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/state': typeof ApiStateRoute
  '/api/support': typeof ApiSupportRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/email-verification': typeof ApiAuthEmailVerificationRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/memory/extract': typeof ApiMemoryExtractRoute
  '/api/admin/files/$fileId': typeof ApiAdminFilesFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/announcements': typeof ApiAnnouncementsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversation-references': typeof ApiConversationReferencesRoute
  '/api/database': typeof ApiDatabaseRoute
  '/api/early-access': typeof ApiEarlyAccessRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/group-invitations': typeof ApiGroupInvitationsRoute
  '/api/group-messages': typeof ApiGroupMessagesRoute
  '/api/groups': typeof ApiGroupsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/state': typeof ApiStateRoute
  '/api/support': typeof ApiSupportRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/email-verification': typeof ApiAuthEmailVerificationRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/memory/extract': typeof ApiMemoryExtractRoute
  '/api/admin/files/$fileId': typeof ApiAdminFilesFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/admin'
    | '/api/announcements'
    | '/api/chat'
    | '/api/conversation-references'
    | '/api/database'
    | '/api/early-access'
    | '/api/feedback'
    | '/api/files'
    | '/api/group-invitations'
    | '/api/group-messages'
    | '/api/groups'
    | '/api/models'
    | '/api/notifications'
    | '/api/providers'
    | '/api/state'
    | '/api/support'
    | '/api/auth/account'
    | '/api/auth/email-verification'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/files/$fileId'
    | '/api/memory/extract'
    | '/api/admin/files/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/admin'
    | '/api/announcements'
    | '/api/chat'
    | '/api/conversation-references'
    | '/api/database'
    | '/api/early-access'
    | '/api/feedback'
    | '/api/files'
    | '/api/group-invitations'
    | '/api/group-messages'
    | '/api/groups'
    | '/api/models'
    | '/api/notifications'
    | '/api/providers'
    | '/api/state'
    | '/api/support'
    | '/api/auth/account'
    | '/api/auth/email-verification'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/files/$fileId'
    | '/api/memory/extract'
    | '/api/admin/files/$fileId'
  id:
    | '__root__'
    | '/'
    | '/api/admin'
    | '/api/announcements'
    | '/api/chat'
    | '/api/conversation-references'
    | '/api/database'
    | '/api/early-access'
    | '/api/feedback'
    | '/api/files'
    | '/api/group-invitations'
    | '/api/group-messages'
    | '/api/groups'
    | '/api/models'
    | '/api/notifications'
    | '/api/providers'
    | '/api/state'
    | '/api/support'
    | '/api/auth/account'
    | '/api/auth/email-verification'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/files/$fileId'
    | '/api/memory/extract'
    | '/api/admin/files/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdminRoute: typeof ApiAdminRouteWithChildren
  ApiAnnouncementsRoute: typeof ApiAnnouncementsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationReferencesRoute: typeof ApiConversationReferencesRoute
  ApiDatabaseRoute: typeof ApiDatabaseRoute
  ApiEarlyAccessRoute: typeof ApiEarlyAccessRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiGroupInvitationsRoute: typeof ApiGroupInvitationsRoute
  ApiGroupMessagesRoute: typeof ApiGroupMessagesRoute
  ApiGroupsRoute: typeof ApiGroupsRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiProvidersRoute: typeof ApiProvidersRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiSupportRoute: typeof ApiSupportRoute
  ApiAuthAccountRoute: typeof ApiAuthAccountRoute
  ApiAuthEmailVerificationRoute: typeof ApiAuthEmailVerificationRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiMemoryExtractRoute: typeof ApiMemoryExtractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support': {
      id: '/api/support'
      path: '/api/support'
      fullPath: '/api/support'
      preLoaderRoute: typeof ApiSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers': {
      id: '/api/providers'
      path: '/api/providers'
      fullPath: '/api/providers'
      preLoaderRoute: typeof ApiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups': {
      id: '/api/groups'
      path: '/api/groups'
      fullPath: '/api/groups'
      preLoaderRoute: typeof ApiGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/group-messages': {
      id: '/api/group-messages'
      path: '/api/group-messages'
      fullPath: '/api/group-messages'
      preLoaderRoute: typeof ApiGroupMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/group-invitations': {
      id: '/api/group-invitations'
      path: '/api/group-invitations'
      fullPath: '/api/group-invitations'
      preLoaderRoute: typeof ApiGroupInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/early-access': {
      id: '/api/early-access'
      path: '/api/early-access'
      fullPath: '/api/early-access'
      preLoaderRoute: typeof ApiEarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/database': {
      id: '/api/database'
      path: '/api/database'
      fullPath: '/api/database'
      preLoaderRoute: typeof ApiDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation-references': {
      id: '/api/conversation-references'
      path: '/api/conversation-references'
      fullPath: '/api/conversation-references'
      preLoaderRoute: typeof ApiConversationReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements': {
      id: '/api/announcements'
      path: '/api/announcements'
      fullPath: '/api/announcements'
      preLoaderRoute: typeof ApiAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/extract': {
      id: '/api/memory/extract'
      path: '/api/memory/extract'
      fullPath: '/api/memory/extract'
      preLoaderRoute: typeof ApiMemoryExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/email-verification': {
      id: '/api/auth/email-verification'
      path: '/api/auth/email-verification'
      fullPath: '/api/auth/email-verification'
      preLoaderRoute: typeof ApiAuthEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/account': {
      id: '/api/auth/account'
      path: '/api/auth/account'
      fullPath: '/api/auth/account'
      preLoaderRoute: typeof ApiAuthAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/files/$fileId': {
      id: '/api/admin/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/api/admin/files/$fileId'
      preLoaderRoute: typeof ApiAdminFilesFileIdRouteImport
      parentRoute: typeof ApiAdminRoute
    }
  }
}

interface ApiAdminRouteChildren {
  ApiAdminFilesFileIdRoute: typeof ApiAdminFilesFileIdRoute
}

const ApiAdminRouteChildren: ApiAdminRouteChildren = {
  ApiAdminFilesFileIdRoute: ApiAdminFilesFileIdRoute,
}

const ApiAdminRouteWithChildren = ApiAdminRoute._addFileChildren(
  ApiAdminRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesFileIdRoute: ApiFilesFileIdRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdminRoute: ApiAdminRouteWithChildren,
  ApiAnnouncementsRoute: ApiAnnouncementsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConversationReferencesRoute: ApiConversationReferencesRoute,
  ApiDatabaseRoute: ApiDatabaseRoute,
  ApiEarlyAccessRoute: ApiEarlyAccessRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiGroupInvitationsRoute: ApiGroupInvitationsRoute,
  ApiGroupMessagesRoute: ApiGroupMessagesRoute,
  ApiGroupsRoute: ApiGroupsRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiProvidersRoute: ApiProvidersRoute,
  ApiStateRoute: ApiStateRoute,
  ApiSupportRoute: ApiSupportRoute,
  ApiAuthAccountRoute: ApiAuthAccountRoute,
  ApiAuthEmailVerificationRoute: ApiAuthEmailVerificationRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiMemoryExtractRoute: ApiMemoryExtractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
