/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStateRouteImport } from './routes/api.state'
import { Route as ApiProvidersRouteImport } from './routes/api.providers'
import { Route as ApiModelsRouteImport } from './routes/api.models'
import { Route as ApiFilesRouteImport } from './routes/api.files'
import { Route as ApiDatabaseRouteImport } from './routes/api.database'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiMemoryExtractRouteImport } from './routes/api.memory.extract'
import { Route as ApiFilesFileIdRouteImport } from './routes/api.files.$fileId'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthAccountRouteImport } from './routes/api.auth.account'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRoute = ApiProvidersRouteImport.update({
  id: '/api/providers',
  path: '/api/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatabaseRoute = ApiDatabaseRouteImport.update({
  id: '/api/database',
  path: '/api/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryExtractRoute = ApiMemoryExtractRouteImport.update({
  id: '/api/memory/extract',
  path: '/api/memory/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAccountRoute = ApiAuthAccountRouteImport.update({
  id: '/api/auth/account',
  path: '/api/auth/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/database': typeof ApiDatabaseRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/state': typeof ApiStateRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/memory/extract': typeof ApiMemoryExtractRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/database': typeof ApiDatabaseRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/state': typeof ApiStateRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/memory/extract': typeof ApiMemoryExtractRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/database': typeof ApiDatabaseRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/state': typeof ApiStateRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/memory/extract': typeof ApiMemoryExtractRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/database'
    | '/api/files'
    | '/api/models'
    | '/api/providers'
    | '/api/state'
    | '/api/auth/account'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/files/$fileId'
    | '/api/memory/extract'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/database'
    | '/api/files'
    | '/api/models'
    | '/api/providers'
    | '/api/state'
    | '/api/auth/account'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/files/$fileId'
    | '/api/memory/extract'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/database'
    | '/api/files'
    | '/api/models'
    | '/api/providers'
    | '/api/state'
    | '/api/auth/account'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/files/$fileId'
    | '/api/memory/extract'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDatabaseRoute: typeof ApiDatabaseRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiModelsRoute: typeof ApiModelsRoute
  ApiProvidersRoute: typeof ApiProvidersRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiAuthAccountRoute: typeof ApiAuthAccountRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiMemoryExtractRoute: typeof ApiMemoryExtractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers': {
      id: '/api/providers'
      path: '/api/providers'
      fullPath: '/api/providers'
      preLoaderRoute: typeof ApiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/database': {
      id: '/api/database'
      path: '/api/database'
      fullPath: '/api/database'
      preLoaderRoute: typeof ApiDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/extract': {
      id: '/api/memory/extract'
      path: '/api/memory/extract'
      fullPath: '/api/memory/extract'
      preLoaderRoute: typeof ApiMemoryExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/account': {
      id: '/api/auth/account'
      path: '/api/auth/account'
      fullPath: '/api/auth/account'
      preLoaderRoute: typeof ApiAuthAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiFilesRouteChildren {
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesFileIdRoute: ApiFilesFileIdRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDatabaseRoute: ApiDatabaseRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiModelsRoute: ApiModelsRoute,
  ApiProvidersRoute: ApiProvidersRoute,
  ApiStateRoute: ApiStateRoute,
  ApiAuthAccountRoute: ApiAuthAccountRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiMemoryExtractRoute: ApiMemoryExtractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
